Non max suppression for line extraction
FelixMoeller3/glue-factory pull request #11
Opened 2024-09-26 14:57 UTC by hardik01shah

Implementation of merging lines using NMS from DeepLSD computes the principal line direction for each connected component of lines, projects all merge candidate line endpoints onto the principal direction vector and chooses the furthest two points as the line endpoints after merge.

To ensure a wireframe like structure at the output of line extraction i.e. line endpoints are a subset of the detected keypoints, this PR modifies NMS to return keypoint indices after line merging instead of the endpoints. After projection onto the principal direction vector, the keypoint (indices) that lead to the furthest points after projection are returned.

Major updates in `gluefactory/models/lines/line_refinement.py`.

2024-09-26 20:08 UTC, RaphaelKreft requested changes
Overall good, but please add the requested comments for clarity

2024-09-26 20:08 UTC, RaphaelKreft commented on gluefactory/models/lines/pold2_extractor.py
> +from gluefactory.models.lines.line_refinement import merge_lines_torch
Added comment for clarity: the method is not used in the extractor currently. It will be built in in another refactoring PR

2024-09-27 13:34 UTC, hardik01shah commented on gluefactory/models/lines/line_refinement.py
>      endpoints barycenter, project the endpoints onto the middle line,
I don't know man, I just took the code from DeepLSD xD
But I think it's the center of gravity of all points

2024-09-27 13:40 UTC, hardik01shah commented on gluefactory/models/lines/line_refinement.py
>      than a threshold and they have a positive overlap.
done.

2024-09-29 20:30 UTC, FelixMoeller3 commented
@hardik01shah is this ready to be merged? Or at least to be raised to a non-draft PR?

2024-09-29 22:53 UTC, hardik01shah commented
@FelixMoeller3 Yes! Requested changes from @RaphaelKreft have been made. Merging.

2024-10-01 20:39 UTC, RaphaelKreft approved these changes
lgtm

2024-10-01 21:31 UTC, merged